### PR TITLE
fix compile and run on linux

### PR DESCRIPTION
**Pull request by witoldo7**
Tested on Linux x64
image

### CODE REVIEW

**Comment by roffe** [comment]
hey man, thanks or the PR. unfortunately this broke the BIN loading on some files.
There is some global state in the C code that makes it not work if one calls the Decode function multiple times without restarting the program between. i fought some with it and didn't find a solution that's why i made the DLL file

```
2023-10-25 19:38:48.100 symbol.go:178 Loading t7biopower.bin
2023-10-25 19:38:48.100 t7_symbol.go:136 0x91> 55565637 
2023-10-25 19:38:48.100 t7_symbol.go:136 0x94> 55569109   
2023-10-25 19:38:48.101 t7_symbol.go:136 0x95> EU0DF22O.55P
2023-10-25 19:38:48.101 t7_symbol.go:136 0x97> 9-5 B235E EC2000 EU @25Mhz    
2023-10-25 19:38:48.102 t7_symbol.go:148 Found binary packed symbol table
2023-10-25 19:38:48.103 t7_symbol.go:439 Address table offset: 0006974C
2023-10-25 19:38:48.103 t7_symbol.go:447 Symbol table offset: 000635B0
2023-10-25 19:38:48.103 t7_symbol.go:451 Symbol table length: 0000618B
2023-10-25 19:38:48.104 t7_symbol.go:294 Loaded 4009 symbols from binary
2023-10-25 19:38:48.122 mainWindow.go:512 Synced 13 / 13 symbols
2023-10-25 19:38:51.047 symbol.go:178 Loading t7biopower.bin
2023-10-25 19:38:51.048 t7_symbol.go:136 0x91> 55565637 
2023-10-25 19:38:51.048 t7_symbol.go:136 0x94> 55569109   
2023-10-25 19:38:51.049 t7_symbol.go:136 0x95> EU0DF22O.55P
2023-10-25 19:38:51.049 t7_symbol.go:136 0x97> 9-5 B235E EC2000 EU @25Mhz    
2023-10-25 19:38:51.050 t7_symbol.go:148 Found binary packed symbol table
2023-10-25 19:38:51.051 t7_symbol.go:439 Address table offset: 0006974C
2023-10-25 19:38:51.051 t7_symbol.go:447 Symbol table offset: 000635B0
2023-10-25 19:38:51.052 t7_symbol.go:451 Symbol table length: 0000618B
2023-10-25 19:38:51.053 t7_symbol.go:294 Loaded 4009 symbols from binary
2023-10-25 19:38:51.054 mainWindow_buttons.go:47 error loading symbols: decoded data size missmatch: 93012 != 93004
2023-10-25 19:39:08.262 symbol.go:178 Loading t7biopower.bin
2023-10-25 19:39:08.262 t7_symbol.go:136 0x91> 55565637 
2023-10-25 19:39:08.262 t7_symbol.go:136 0x94> 55569109   
2023-10-25 19:39:08.262 t7_symbol.go:136 0x95> EU0DF22O.55P
2023-10-25 19:39:08.262 t7_symbol.go:136 0x97> 9-5 B235E EC2000 EU @25Mhz    
2023-10-25 19:39:08.262 t7_symbol.go:148 Found binary packed symbol table
2023-10-25 19:39:08.263 t7_symbol.go:439 Address table offset: 0006974C
2023-10-25 19:39:08.263 t7_symbol.go:447 Symbol table offset: 000635B0
2023-10-25 19:39:08.263 t7_symbol.go:451 Symbol table length: 0000618B
2023-10-25 19:39:08.264 t7_symbol.go:294 Loaded 4009 symbols from binary
2023-10-25 19:39:08.279 mainWindow.go:512 Synced 13 / 13 symbols
2023-10-25 19:39:12.865 symbol.go:178 Loading t7biopower.bin
2023-10-25 19:39:12.865 t7_symbol.go:136 0x91> 55565637 
2023-10-25 19:39:12.866 t7_symbol.go:136 0x94> 55569109   
2023-10-25 19:39:12.866 t7_symbol.go:136 0x95> EU0DF22O.55P
2023-10-25 19:39:12.866 t7_symbol.go:136 0x97> 9-5 B235E EC2000 EU @25Mhz    
2023-10-25 19:39:12.867 t7_symbol.go:148 Found binary packed symbol table
2023-10-25 19:39:12.869 t7_symbol.go:439 Address table offset: 0006974C
2023-10-25 19:39:12.869 t7_symbol.go:447 Symbol table offset: 000635B0
2023-10-25 19:39:12.869 t7_symbol.go:451 Symbol table length: 0000618B
2023-10-25 19:39:12.870 t7_symbol.go:294 Loaded 4009 symbols from binary
2023-10-25 19:39:12.872 mainWindow_buttons.go:47 error loading symbols: decoded data size missmatch: 93012 != 93004
2023-10-25 19:39:17.560 symbol.go:178 Loading t7biopower.bin
2023-10-25 19:39:17.561 t7_symbol.go:136 0x91> 55565637 
2023-10-25 19:39:17.561 t7_symbol.go:136 0x94> 55569109   
2023-10-25 19:39:17.562 t7_symbol.go:136 0x95> EU0DF22O.55P
2023-10-25 19:39:17.562 t7_symbol.go:136 0x97> 9-5 B235E EC2000 EU @25Mhz    
2023-10-25 19:39:17.562 t7_symbol.go:148 Found binary packed symbol table
2023-10-25 19:39:17.564 t7_symbol.go:439 Address table offset: 0006974C
2023-10-25 19:39:17.564 t7_symbol.go:447 Symbol table offset: 000635B0
2023-10-25 19:39:17.564 t7_symbol.go:451 Symbol table length: 0000618B
2023-10-25 19:39:17.565 t7_symbol.go:294 Loaded 4009 symbols from binary
2023-10-25 19:39:17.569 mainWindow_buttons.go:47 error loading symbols: decoded data size missmatch: 93032 != 93004
```
something is leaking since the size returned increases each time i use Decode()

**Comment by witoldo7** [comment]
Could you send me test bins, I can dig more. On Linux I do not faced this issue

**Comment by witoldo7** [comment]
kk, I will dig more on it

**Comment by roffe** [comment]
[t7biopower.zip](https://github.com/roffe/txlogger/files/13169215/t7biopower.zip)

**Comment by roffe** [comment]
add 
```c
    getlen = 0;
    getbuf = 0;
```
just before the `return count` in Decode() and the problem is fixed

**Comment by roffe** [comment]
i've fixed it in master. big thank you. now we don't rely on that pesky dll file 👍🏻

**Pull request merged**
